puts :teste.object_id
puts :teste.object_id
puts :teste.object_id
puts :teste.object_id
puts "----------------------"
puts "teste".object_id
puts "teste".object_id
puts "teste".object_id
puts "teste".object_id